const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Read the pre-built CSS (skip Tailwind build for now)
console.log('Reading pre-built Tailwind CSS...');
const tailwindCSS = fs.readFileSync('./dist/tailwind.css', 'utf8');
console.log('✓ Tailwind CSS loaded successfully');

// Read script files
const converterScript = fs.readFileSync('./src/scripts/converter.js', 'utf8');
const pdfScript = fs.readFileSync('./src/scripts/pdf.js', 'utf8');

// Generate the final worker.js
const workerTemplate = `// This file is auto-generated by build.js
// Do not edit directly - edit files in src/ instead

// Embedded Tailwind CSS
const TAILWIND_CSS = \`${tailwindCSS.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;

// Embedded Scripts
const CONVERTER_SCRIPT = \`${converterScript.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
const PDF_SCRIPT = \`${pdfScript.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Note: Removed COEP headers that were blocking external resources
    const headers = {};

    // --- 1. ROOT PATH (App Hub) ---
    if (url.pathname === "/") {
      return new Response(renderIndex(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 2. CSS STYLESHEET ---
    if (url.pathname === "/style.css") {
      return new Response(TAILWIND_CSS, {
        headers: { "Content-Type": "text/css" },
      });
    }

    // --- 3. CONVERTER APP ---
    if (url.pathname === "/converter") {
      return new Response(renderConverter(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 4. PDF TOOLS APP ---
    if (url.pathname === "/pdf") {
      return new Response(renderPDFTools(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 404 NOT FOUND ---
    return new Response("404 - Page Not Found", { status: 404 });
  }
};

function renderIndex() {
  return \`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | App Hub</title>
    <link rel="stylesheet" href="/style.css">
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 select-none">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">iridescence</span></h1>
        </div>
        <div class="hidden md:flex items-center gap-2 text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200">
            <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            ALL SYSTEMS OPERATIONAL
        </div>
    </header>
    <main class="flex-1 overflow-y-auto p-6 md:p-10 fade-in">
        <div class="max-w-7xl mx-auto space-y-12 pb-20">
            <div>
                <h2 class="text-4xl font-extrabold mb-2 text-slate-900 tracking-tight">App Hub</h2>
                <p class="text-lg text-slate-500 max-w-2xl">Access all your tools, vaults, and projects from one secure location.</p>
            </div>
            <section>
                <div class="flex items-center gap-2 mb-6"><span class="text-2xl">🛠️</span><h3 class="text-xl font-bold text-slate-800">Tools</h3></div>
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
                    <a href="/pdf" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-indigo-50 text-indigo-600 transition-transform group-hover:scale-110">📚</div>
                        <div><h4 class="font-bold text-lg text-slate-800">111 PDF Tools</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Secure, client-side PDF editing and merging suite.</p></div>
                    </a>
                    <a href="/converter" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-emerald-50 text-emerald-600 transition-transform group-hover:scale-110">🔄</div>
                        <div><h4 class="font-bold text-lg text-slate-800">111 Converter</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Fast universal file conversion utility.</p></div>
                    </a>
                </div>
            </section>
            <hr class="border-slate-200">
            <section>
                <div class="flex items-center gap-2 mb-6"><span class="text-2xl">✨</span><h3 class="text-xl font-bold text-slate-800">Other Webapps</h3></div>
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
                    <a href="/vault" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-slate-100 text-slate-600 transition-transform group-hover:scale-110">🔒</div>
                        <div><h4 class="font-bold text-lg text-slate-800">Vault</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Secure personal storage and data archive.</p></div>
                    </a>
                    <a href="/habits" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-orange-50 text-orange-600 transition-transform group-hover:scale-110">📈</div>
                        <div><h4 class="font-bold text-lg text-slate-800">Habits Tracker</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Daily routines, goals, and progress monitoring.</p></div>
                    </a>
                </div>
            </section>
        </div>
    </main>
</body>
</html>\`;
}

function renderConverter() {
  return \`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | Universal Converter</title>
    <link rel="stylesheet" href="/style.css">
    <script src="https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js"></script>
    <script src="https://unpkg.com/mammoth@1.6.0/mammoth.browser.min.js"></script>
    <script src="https://unpkg.com/html2pdf.js@0.10.1/dist/html2pdf.bundle.min.js"></script>
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 cursor-pointer select-none" onclick="window.location.href='/'">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">converter</span></h1>
        </div>
        <div id="engine-status" class="flex items-center gap-2 text-xs font-semibold text-orange-500 bg-orange-50 px-3 py-1.5 rounded-full border border-orange-200">
            <span class="w-2 h-2 rounded-full bg-orange-500 animate-pulse"></span>
            Loading Engine...
        </div>
    </header>

    <main class="flex-1 overflow-hidden relative flex flex-col">
        <div class="bg-white border-b border-slate-200 p-4 flex flex-col md:flex-row items-center justify-between shadow-sm z-10 gap-4">
            <div class="text-sm text-slate-500 font-medium">
                Supports: <span class="text-slate-800">Video, Audio, Images, Documents</span>
            </div>

            <div class="flex items-center gap-3">
                <button onclick="document.getElementById('folder-upload').click()" class="bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2 rounded-lg font-bold text-sm border border-slate-200">
                    📂 Add Folder
                </button>
                <button onclick="document.getElementById('file-upload').click()" class="bg-slate-800 hover:bg-slate-900 text-white px-4 py-2 rounded-lg font-bold text-sm shadow-md">
                    + Add Files
                </button>
                <button id="convert-all-btn" onclick="convertAll()" class="bg-indigo-500 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg font-bold text-sm shadow-md transition-all opacity-50 cursor-not-allowed" disabled>
                    Convert All
                </button>
            </div>
        </div>

        <div id="drop-zone" class="flex-1 overflow-y-auto p-4 md:p-8 relative bg-slate-50">
            <div id="empty-state" class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none opacity-100 transition-opacity">
                <div class="w-24 h-24 bg-indigo-50 rounded-full flex items-center justify-center text-5xl mb-6 text-indigo-500 shadow-inner">♻️</div>
                <h3 class="text-2xl font-bold text-slate-700 mb-2">Universal Converter</h3>
                <p class="text-slate-500 text-center max-w-md">Drag & Drop files or folders here.<br>Convert MP4, AVI, MOV, MP3, WAV, PNG, JPG, WEBP, DOCX and more.</p>
            </div>
            <div id="file-list" class="grid grid-cols-1 gap-4 max-w-5xl mx-auto pb-20 hidden"></div>
        </div>

        <input type="file" id="file-upload" class="hidden" multiple>
        <input type="file" id="folder-upload" class="hidden" multiple webkitdirectory directory>
    </main>

    <script>\${CONVERTER_SCRIPT}</script>
</body>
</html>\`;
}

function renderPDFTools() {
  return \`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | PDF Tools</title>
    <link rel="stylesheet" href="/style.css">
    <script src="https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.15.0/Sortable.min.js"></script>
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 cursor-pointer select-none" onclick="window.location.href='/'">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">iridescence</span></h1>
        </div>
        <div class="hidden md:flex items-center gap-2 text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200">
            <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            CLIENT-SIDE ONLY
        </div>
    </header>

    <main class="flex-1 overflow-hidden relative">
        <div id="view-dashboard" class="h-full overflow-y-auto p-6 md:p-10 fade-in">
            <div class="max-w-7xl mx-auto">
                <div class="mb-12">
                    <h2 class="text-3xl font-bold mb-2 text-slate-900">PDF Tools</h2>
                    <p class="text-slate-500">Secure processing in your browser.</p>
                </div>
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5" id="tool-grid"></div>
            </div>
        </div>

        <div id="view-workspace" class="hidden h-full flex flex-col bg-slate-50">
            <div class="bg-white border-b border-slate-200 p-4 flex flex-col md:flex-row items-center justify-between shadow-sm z-10 gap-4">
                <div class="flex items-center gap-4 w-full md:w-auto">
                    <button onclick="goHome()" class="text-slate-500 hover:text-slate-800 font-medium px-2 py-1 hover:bg-slate-100 rounded">← Back</button>
                    <div class="h-6 w-px bg-slate-200 hidden md:block"></div>
                    <h2 id="tool-name" class="font-bold text-lg text-slate-800">Tool Name</h2>
                </div>
                <div id="tool-settings" class="flex-1 flex flex-wrap items-center justify-center md:justify-end gap-3"></div>
                <div class="flex items-center gap-2 w-full md:w-auto justify-end">
                    <button onclick="document.getElementById('file-upload').click()" class="bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2 rounded-lg font-bold text-sm border border-slate-200">
                        + Add Files
                    </button>
                    <button id="btn-process" onclick="processFiles()" class="bg-indigo-500 hover:bg-indigo-600 text-white px-6 py-2 rounded-lg font-bold text-sm shadow-md transition-all flex items-center gap-2">
                        Download PDF
                    </button>
                </div>
            </div>

            <div id="canvas-area" class="flex-1 overflow-y-auto p-4 md:p-8 relative">
                <div id="empty-state" class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none opacity-60">
                    <div class="w-24 h-24 bg-slate-200 rounded-full flex items-center justify-center text-4xl mb-4 text-slate-400">📂</div>
                    <h3 class="text-xl font-bold text-slate-400">Drop files here</h3>
                </div>
                <div id="grid-container" class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-6 gap-6 max-w-7xl mx-auto pb-20"></div>
            </div>
            <input type="file" id="file-upload" class="hidden" multiple>
        </div>
    </main>

    <div id="toast" class="fixed bottom-6 right-6 bg-slate-800 text-white px-6 py-4 rounded-lg shadow-2xl transform translate-y-32 opacity-0 transition-all duration-300 z-50 flex items-center gap-4">
        <div class="loader"></div>
        <span id="toast-msg" class="font-medium">Processing...</span>
    </div>

    <script>\${PDF_SCRIPT}</script>
</body>
</html>\`;
}`;

// Create output directory
if (!fs.existsSync('./dist')) {
  fs.mkdirSync('./dist');
}

// Write the final worker.js
fs.writeFileSync('./worker.js', workerTemplate);
console.log('✓ worker.js built successfully');

console.log('\\n🎉 Build complete! Run "wrangler deploy" to deploy.');