// This file is auto-generated by build.js
// Do not edit directly - edit files in src/ instead

// Embedded Tailwind CSS
const TAILWIND_CSS = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

/* Tailwind CSS v3.4.0 - Minimal build with only used classes */

*,::before,::after{box-sizing:border-box;border-width:0;border-style:solid;border-color:#e5e7eb}
::before,::after{--tw-content:''}
html{line-height:1.5;-webkit-text-size-adjust:100%;-moz-tab-size:4;tab-size:4;font-family:ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";font-feature-settings:normal}
body{margin:0;line-height:inherit}
hr{height:0;color:inherit;border-top-width:1px}
abbr:where([title]){text-decoration:underline dotted}
h1,h2,h3,h4,h5,h6{font-size:inherit;font-weight:inherit}
a{color:inherit;text-decoration:inherit}
b,strong{font-weight:bolder}
code,kbd,samp,pre{font-family:ui-monospace, SFMono-Regular, "Consolas", "Liberation Mono", "Menlo", monospace;font-size:1em}
small{font-size:80%}
sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}
sub{bottom:-.25em}
sup{top:-.5em}
table{text-indent:0;border-color:inherit;border-collapse:collapse}
button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;font-weight:inherit;line-height:inherit;color:inherit;margin:0;padding:0}
button,select{text-transform:none}
button,[type='button'],[type='reset'],[type='submit']{-webkit-appearance:button;background-color:transparent;background-image:none}
:-moz-focusring{outline:auto}
:-moz-ui-invalid{box-shadow:none}
progress{vertical-align:baseline}
::-webkit-inner-spin-button,::-webkit-outer-spin-button{height:auto}
[type='search']{-webkit-appearance:textfield;outline-offset:-2px}
::-webkit-search-decoration{-webkit-appearance:none}
::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}
summary{display:list-item}
blockquote,dl,dd,h1,h2,h3,h4,h5,h6,hr,figure,p,pre{margin:0}
fieldset{margin:0;padding:0}
legend{padding:0}
ol,ul,menu{list-style:none;margin:0;padding:0}
textarea{resize:vertical}
input::placeholder,textarea::placeholder{opacity:1;color:#9ca3af}
button,[role="button"]{cursor:pointer}
:disabled{cursor:default}
img,svg,video,canvas,audio,iframe,embed,object{display:block;vertical-align:middle}
img,video{max-width:100%;height:auto}
[hidden]{display:none}

.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border-width:0}
.pointer-events-none{pointer-events:none}
.absolute{position:absolute}
.relative{position:relative}
.fixed{position:fixed}
.inset-0{top:0px;right:0px;bottom:0px;left:0px}
.left-0{left:0px}
.right-0{right:0px}
.top-0{top:0px}
.bottom-2{bottom:0.5rem}
.right-2{right:0.5rem}
.left-2{left:0.5rem}
.top-2{top:0.5rem}
.left-50\%{left:50%}
.top-50\%{top:50%}
.bottom-6{bottom:1.5rem}
.right-6{right:1.5rem}
.z-10{z-index:10}
.z-20{z-index:20}
.z-50{z-index:50}
.z-100{z-index:100}
.block{display:block}
.inline-block{display:inline-block}
.flex{display:flex}
.inline-flex{display:inline-flex}
.table{display:table}
.grid{display:grid}
.hidden{display:none}
.h-2{height:0.5rem}
.h-2\.5{height:0.625rem}
.h-6{height:1.5rem}
.h-7{height:1.75rem}
.h-8{height:2rem}
.h-12{height:3rem}
.h-14{height:3.5rem}
.h-16{height:4rem}
.h-24{height:6rem}
.h-40{height:10rem}
.h-56{height:14rem}
.h-full{height:100%}
.h-screen{height:100vh}
.min-w-0{min-width:0px}
.w-2{width:0.5rem}
.w-7{width:1.75rem}
.w-8{width:2rem}
.w-12{width:3rem}
.w-14{width:3.5rem}
.w-24{width:6rem}
.w-32{width:8rem}
.w-40{width:10rem}
.w-48{width:12rem}
.w-full{width:100%}
.max-w-md{max-width:28rem}
.max-w-2xl{max-width:42rem}
.max-w-5xl{max-width:64rem}
.max-w-7xl{max-width:80rem}
.flex-1{flex:1 1 0%}
.flex-shrink-0{flex-shrink:0}
.-translate-x-1\/2{--tw-translate-x:-50%;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
.-translate-y-1\/2{--tw-translate-y:-50%;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
.translate-y-32{--tw-translate-y:8rem;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
.scale-95{--tw-scale-x:.95;--tw-scale-y:.95;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
.transform{transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
@keyframes pulse{50%{opacity:.5}}
.animate-pulse{animation:pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite}
.cursor-pointer{cursor:pointer}
.cursor-not-allowed{cursor:not-allowed}
.cursor-grab{cursor:grab}
.cursor-grabbing{cursor:grabbing}
.select-none{user-select:none}
.grid-cols-1{grid-template-columns:repeat(1, minmax(0, 1fr))}
.grid-cols-2{grid-template-columns:repeat(2, minmax(0, 1fr))}
.flex-col{flex-direction:column}
.flex-wrap{flex-wrap:wrap}
.items-start{align-items:flex-start}
.items-end{align-items:flex-end}
.items-center{align-items:center}
.justify-start{justify-content:flex-start}
.justify-end{justify-content:flex-end}
.justify-center{justify-content:center}
.justify-between{justify-content:space-between}
.gap-2{gap:0.5rem}
.gap-3{gap:0.75rem}
.gap-4{gap:1rem}
.gap-5{gap:1.25rem}
.gap-6{gap:1.5rem}
.space-y-12 > :not([hidden]) ~ :not([hidden]){--tw-space-y-reverse:0;margin-top:calc(3rem * calc(1 - var(--tw-space-y-reverse)));margin-bottom:calc(3rem * var(--tw-space-y-reverse))}
.overflow-hidden{overflow:hidden}
.overflow-y-auto{overflow-y:auto}
.truncate{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.rounded{border-radius:0.25rem}
.rounded-lg{border-radius:0.5rem}
.rounded-xl{border-radius:0.75rem}
.rounded-2xl{border-radius:1rem}
.rounded-full{border-radius:9999px}
.border{border-width:1px}
.border-2{border-width:2px}
.border-3{border-width:3px}
.border-b{border-bottom-width:1px}
.border-t{border-top-width:1px}
.border-dashed{border-style:dashed}
.border-solid{border-style:solid}
.border-transparent{border-color:transparent}
.border-slate-100{--tw-border-opacity:1;border-color:rgb(241 245 249 / var(--tw-border-opacity))}
.border-slate-200{--tw-border-opacity:1;border-color:rgb(226 232 240 / var(--tw-border-opacity))}
.border-slate-300{--tw-border-opacity:1;border-color:rgb(203 213 225 / var(--tw-border-opacity))}
.border-indigo-500{--tw-border-opacity:1;border-color:rgb(99 102 241 / var(--tw-border-opacity))}
.border-orange-200{--tw-border-opacity:1;border-color:rgb(254 215 170 / var(--tw-border-opacity))}
.border-emerald-200{--tw-border-opacity:1;border-color:rgb(167 243 208 / var(--tw-border-opacity))}
.border-blue-200{--tw-border-opacity:1;border-color:rgb(191 219 254 / var(--tw-border-opacity))}
.bg-white{--tw-bg-opacity:1;background-color:rgb(255 255 255 / var(--tw-bg-opacity))}
.bg-slate-50{--tw-bg-opacity:1;background-color:rgb(248 250 252 / var(--tw-bg-opacity))}
.bg-slate-100{--tw-bg-opacity:1;background-color:rgb(241 245 249 / var(--tw-bg-opacity))}
.bg-slate-200{--tw-bg-opacity:1;background-color:rgb(226 232 240 / var(--tw-bg-opacity))}
.bg-slate-800{--tw-bg-opacity:1;background-color:rgb(30 41 59 / var(--tw-bg-opacity))}
.bg-slate-900{--tw-bg-opacity:1;background-color:rgb(15 23 42 / var(--tw-bg-opacity))}
.bg-indigo-50{--tw-bg-opacity:1;background-color:rgb(238 242 255 / var(--tw-bg-opacity))}
.bg-indigo-500{--tw-bg-opacity:1;background-color:rgb(99 102 241 / var(--tw-bg-opacity))}
.bg-emerald-50{--tw-bg-opacity:1;background-color:rgb(236 253 245 / var(--tw-bg-opacity))}
.bg-emerald-500{--tw-bg-opacity:1;background-color:rgb(16 185 129 / var(--tw-bg-opacity))}
.bg-orange-50{--tw-bg-opacity:1;background-color:rgb(255 247 237 / var(--tw-bg-opacity))}
.bg-blue-50{--tw-bg-opacity:1;background-color:rgb(239 246 255 / var(--tw-bg-opacity))}
.bg-rose-50{--tw-bg-opacity:1;background-color:rgb(255 241 242 / var(--tw-bg-opacity))}
.bg-teal-50{--tw-bg-opacity:1;background-color:rgb(240 253 250 / var(--tw-bg-opacity))}
.bg-purple-50{--tw-bg-opacity:1;background-color:rgb(250 245 255 / var(--tw-bg-opacity))}
.bg-gray-50{--tw-bg-opacity:1;background-color:rgb(249 250 251 / var(--tw-bg-opacity))}
.bg-gradient-to-br{background-image:linear-gradient(to bottom right, var(--tw-gradient-stops))}
.from-indigo-500{--tw-gradient-from:#6366f1;--tw-gradient-to:rgb(99 102 241 / 0);--tw-gradient-stops:var(--tw-gradient-from), var(--tw-gradient-to)}
.to-rose-500{--tw-gradient-to:#f43f5e}
.object-contain{object-fit:contain}
.p-1\.5{padding:0.375rem}
.p-2{padding:0.5rem}
.p-3{padding:0.75rem}
.p-4{padding:1rem}
.p-6{padding:1.5rem}
.px-2{padding-left:0.5rem;padding-right:0.5rem}
.px-3{padding-left:0.75rem;padding-right:0.75rem}
.px-4{padding-left:1rem;padding-right:1rem}
.px-6{padding-left:1.5rem;padding-right:1.5rem}
.py-1{padding-top:0.25rem;padding-bottom:0.25rem}
.py-1\.5{padding-top:0.375rem;padding-bottom:0.375rem}
.py-2{padding-top:0.5rem;padding-bottom:0.5rem}
.py-4{padding-top:1rem;padding-bottom:1rem}
.pb-20{padding-bottom:5rem}
.pt-0{padding-top:0px}
.pl-0{padding-left:0px}
.pr-0{padding-right:0px}
.text-left{text-align:left}
.text-center{text-align:center}
.text-right{text-align:right}
.font-sans{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"}
.text-xs{font-size:0.75rem;line-height:1rem}
.text-sm{font-size:0.875rem;line-height:1.25rem}
.text-lg{font-size:1.125rem;line-height:1.75rem}
.text-xl{font-size:1.25rem;line-height:1.75rem}
.text-2xl{font-size:1.5rem;line-height:2rem}
.text-3xl{font-size:1.875rem;line-height:2.25rem}
.text-4xl{font-size:2.25rem;line-height:2.5rem}
.font-medium{font-weight:500}
.font-semibold{font-weight:600}
.font-bold{font-weight:700}
.font-extrabold{font-weight:800}
.leading-relaxed{line-height:1.625}
.tracking-tight{letter-spacing:-0.025em}
.text-white{--tw-text-opacity:1;color:rgb(255 255 255 / var(--tw-text-opacity))}
.text-slate-400{--tw-text-opacity:1;color:rgb(148 163 184 / var(--tw-text-opacity))}
.text-slate-500{--tw-text-opacity:1;color:rgb(100 116 139 / var(--tw-text-opacity))}
.text-slate-600{--tw-text-opacity:1;color:rgb(71 85 105 / var(--tw-text-opacity))}
.text-slate-700{--tw-text-opacity:1;color:rgb(51 65 85 / var(--tw-text-opacity))}
.text-slate-800{--tw-text-opacity:1;color:rgb(30 41 59 / var(--tw-text-opacity))}
.text-slate-900{--tw-text-opacity:1;color:rgb(15 23 42 / var(--tw-text-opacity))}
.text-indigo-500{--tw-text-opacity:1;color:rgb(99 102 241 / var(--tw-text-opacity))}
.text-indigo-600{--tw-text-opacity:1;color:rgb(79 70 229 / var(--tw-text-opacity))}
.text-emerald-600{--tw-text-opacity:1;color:rgb(5 150 105 / var(--tw-text-opacity))}
.text-orange-500{--tw-text-opacity:1;color:rgb(249 115 22 / var(--tw-text-opacity))}
.text-orange-600{--tw-text-opacity:1;color:rgb(234 88 12 / var(--tw-text-opacity))}
.text-blue-500{--tw-text-opacity:1;color:rgb(59 130 246 / var(--tw-text-opacity))}
.text-blue-600{--tw-text-opacity:1;color:rgb(37 99 235 / var(--tw-text-opacity))}
.text-rose-500{--tw-text-opacity:1;color:rgb(244 63 94 / var(--tw-text-opacity))}
.text-teal-600{--tw-text-opacity:1;color:rgb(13 148 136 / var(--tw-text-opacity))}
.text-purple-600{--tw-text-opacity:1;color:rgb(147 51 234 / var(--tw-text-opacity))}
.text-gray-600{--tw-text-opacity:1;color:rgb(75 85 99 / var(--tw-text-opacity))}
.text-red-500{--tw-text-opacity:1;color:rgb(239 68 68 / var(--tw-text-opacity))}
.text-red-600{--tw-text-opacity:1;color:rgb(220 38 38 / var(--tw-text-opacity))}
.no-underline{text-decoration-line:none}
.opacity-0{opacity:0}
.opacity-50{opacity:0.5}
.opacity-60{opacity:0.6}
.opacity-100{opacity:1}
.shadow{--tw-shadow:0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);--tw-shadow-colored:0 1px 3px 0 var(--tw-shadow-color), 0 1px 2px -1px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.shadow-sm{--tw-shadow:0 1px 2px 0 rgb(0 0 0 / 0.05);--tw-shadow-colored:0 1px 2px 0 var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.shadow-md{--tw-shadow:0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);--tw-shadow-colored:0 4px 6px -1px var(--tw-shadow-color), 0 2px 4px -2px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.shadow-lg{--tw-shadow:0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);--tw-shadow-colored:0 10px 15px -3px var(--tw-shadow-color), 0 4px 6px -4px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.shadow-2xl{--tw-shadow:0 25px 50px -12px rgb(0 0 0 / 0.25);--tw-shadow-colored:0 25px 50px -12px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.shadow-inner{--tw-shadow:inset 0 2px 4px 0 rgb(0 0 0 / 0.06);--tw-shadow-colored:inset 0 2px 4px 0 var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}
.outline-none{outline:2px solid transparent;outline-offset:2px}
.ring-1{--tw-ring-offset-shadow:var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);--tw-ring-shadow:var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);box-shadow:var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000)}
.ring-indigo-500{--tw-ring-opacity:1;--tw-ring-color:rgb(99 102 241 / var(--tw-ring-opacity))}
.duration-300{transition-duration:300ms}
.ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1)}

/* Focus states */
.focus\:border-indigo-500:focus{--tw-border-opacity:1;border-color:rgb(99 102 241 / var(--tw-border-opacity))}
.focus\:ring-1:focus{--tw-ring-offset-shadow:var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);--tw-ring-shadow:var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);box-shadow:var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000)}
.focus\:ring-indigo-500:focus{--tw-ring-opacity:1;--tw-ring-color:rgb(99 102 241 / var(--tw-ring-opacity))}

/* Hover states */
.hover\:bg-slate-100:hover{--tw-bg-opacity:1;background-color:rgb(241 245 249 / var(--tw-bg-opacity))}
.hover\:bg-slate-200:hover{--tw-bg-opacity:1;background-color:rgb(226 232 240 / var(--tw-bg-opacity))}
.hover\:bg-slate-900:hover{--tw-bg-opacity:1;background-color:rgb(15 23 42 / var(--tw-bg-opacity))}
.hover\:bg-indigo-600:hover{--tw-bg-opacity:1;background-color:rgb(79 70 229 / var(--tw-bg-opacity))}
.hover\:bg-indigo-700:hover{--tw-bg-opacity:1;background-color:rgb(67 56 202 / var(--tw-bg-opacity))}
.hover\:bg-emerald-600:hover{--tw-bg-opacity:1;background-color:rgb(5 150 105 / var(--tw-bg-opacity))}
.hover\:text-indigo-500:hover{--tw-text-opacity:1;color:rgb(99 102 241 / var(--tw-text-opacity))}
.hover\:text-slate-800:hover{--tw-text-opacity:1;color:rgb(30 41 59 / var(--tw-text-opacity))}
.hover\:text-red-500:hover{--tw-text-opacity:1;color:rgb(239 68 68 / var(--tw-text-opacity))}
.hover\:text-red-600:hover{--tw-text-opacity:1;color:rgb(220 38 38 / var(--tw-text-opacity))}
.hover\:shadow-md:hover{--tw-shadow:0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);--tw-shadow-colored:0 4px 6px -1px var(--tw-shadow-color), 0 2px 4px -2px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)}

/* Group hover states */
.group:hover .group-hover\:scale-110{--tw-scale-x:1.1;--tw-scale-y:1.1;transform:translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}
.group:hover .group-hover\:opacity-100{opacity:1}

/* Responsive breakpoints */
@media (min-width: 640px) {
  .sm\:grid-cols-2{grid-template-columns:repeat(2, minmax(0, 1fr))}
  .sm\:grid-cols-3{grid-template-columns:repeat(3, minmax(0, 1fr))}
}

@media (min-width: 768px) {
  .md\:flex{display:flex}
  .md\:hidden{display:none}
  .md\:w-auto{width:auto}
  .md\:w-32{width:8rem}
  .md\:flex-row{flex-direction:row}
  .md\:justify-end{justify-content:flex-end}
  .md\:p-8{padding:2rem}
  .md\:p-10{padding:2.5rem}
  .md\:text-left{text-align:left}
  .md\:block{display:block}
}

@media (min-width: 1024px) {
  .lg\:grid-cols-4{grid-template-columns:repeat(4, minmax(0, 1fr))}
}

@media (min-width: 1280px) {
  .xl\:grid-cols-6{grid-template-columns:repeat(6, minmax(0, 1fr))}
}

/* Transition and animation utilities */
.transition{transition-property:color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms}
.transition-all{transition-property:all;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms}
.transition-colors{transition-property:color, background-color, border-color, text-decoration-color, fill, stroke;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms}
.transition-transform{transition-property:transform;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms}

/* Custom animations */
.fade-in { 
  animation: fadeIn 0.4s ease-out; 
}

@keyframes fadeIn { 
  from { opacity: 0; transform: translateY(15px); } 
  to { opacity: 1; transform: translateY(0); } 
}

/* Card Interactive Styling */
.tool-card {
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  cursor: pointer;
}

.tool-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 20px -8px rgba(99, 102, 241, 0.25);
  border-color: #6366f1;
}

/* Converter Styles */
.drag-over {
  background-color: #e0e7ff !important;
  border: 2px dashed #6366f1;
}

::-webkit-scrollbar { width: 8px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: #94a3b8; }

.spin { animation: spin 1s linear infinite; }
@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }

.progress-bar { transition: width 0.2s linear; }

/* PDF Tools Styles */
.sortable-ghost {
  opacity: 0.4;
  background: #e0e7ff;
  border: 2px dashed #6366f1;
}

.sortable-drag {
  cursor: grabbing;
  opacity: 1;
  background: white;
  transform: scale(1.05) rotate(2deg);
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
  z-index: 100;
}

.drag-handle {
  cursor: grab;
  touch-action: none;
}

.drag-handle:active { cursor: grabbing; }

.thumb-area {
  transition: all 0.15s ease;
  border: 3px solid transparent;
}

.thumb-area.selected {
  border-color: #6366f1;
  background-color: #e0e7ff;
  box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.2);
  transform: scale(0.95);
}

.thumb-area.selected::after {
  content: '✓';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 2rem;
  color: #6366f1;
  font-weight: bold;
  z-index: 20;
  background: rgba(255, 255, 255, 0.9);
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}

.loader {
  border: 3px solid rgba(255,255,255,0.3);
  border-top: 3px solid white;
  border-radius: 50%;
  width: 20px;
  height: 20px;
  animation: spin 1s linear infinite;
}`;

// Embedded Scripts
const CONVERTER_SCRIPT = `const { createFFmpeg, fetchFile } = FFmpeg;
let ffmpeg = null;

const FORMATS = {
    video: ["mp4", "webm", "avi", "mov", "mkv", "flv", "gif", "mp3"],
    audio: ["mp3", "wav", "aac", "ogg", "m4a", "flac"],
    image: ["jpg", "png", "webp", "bmp", "tiff", "ico", "gif"],
    document: ["pdf"]
};

const getType = (file) => {
    if (file.type.startsWith("video/")) return "video";
    if (file.type.startsWith("audio/")) return "audio";
    if (file.type.startsWith("image/")) return "image";
    const ext = file.name.split(".").pop().toLowerCase();
    if (["mkv", "avi", "mov"].includes(ext)) return "video";
    if (["docx", "doc"].includes(ext)) return "document";
    return "unknown";
};

let files = [];

const dom = {
    dropZone: document.getElementById("drop-zone"),
    fileList: document.getElementById("file-list"),
    empty: document.getElementById("empty-state"),
    status: document.getElementById("engine-status"),
    convertBtn: document.getElementById("convert-all-btn")
};

async function initFFmpeg() {
    try {
        if (typeof SharedArrayBuffer === "undefined") {
            dom.status.className = "flex items-center gap-2 text-xs font-semibold text-blue-600 bg-blue-50 px-3 py-1.5 rounded-full border border-blue-200";
            dom.status.innerHTML = '<span class="w-2 h-2 rounded-full bg-blue-500"></span> Limited Mode (No Video/Audio)';
            console.log("SharedArrayBuffer not available - FFmpeg disabled");
            return;
        }
        ffmpeg = createFFmpeg({
            log: true,
            corePath: "https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js"
        });
        await ffmpeg.load();
        dom.status.className = "flex items-center gap-2 text-xs font-semibold text-emerald-600 bg-emerald-50 px-3 py-1.5 rounded-full border border-emerald-200";
        dom.status.innerHTML = '<span class="w-2 h-2 rounded-full bg-emerald-500"></span> Engine Ready';
        console.log("FFmpeg Loaded");
    } catch (e) {
        console.error(e);
        dom.status.className = "flex items-center gap-2 text-xs font-semibold text-blue-600 bg-blue-50 px-3 py-1.5 rounded-full border border-blue-200";
        dom.status.innerHTML = '<span class="w-2 h-2 rounded-full bg-blue-500"></span> Limited Mode (Images/Docs Only)';
    }
}
initFFmpeg();

["dragenter", "dragover", "dragleave", "drop"].forEach(eventName => {
    dom.dropZone.addEventListener(eventName, preventDefaults, false);
});

function preventDefaults(e) { e.preventDefault(); e.stopPropagation(); }

dom.dropZone.addEventListener("dragenter", () => dom.dropZone.classList.add("drag-over"));
dom.dropZone.addEventListener("dragleave", () => dom.dropZone.classList.remove("drag-over"));
dom.dropZone.addEventListener("drop", (e) => {
    dom.dropZone.classList.remove("drag-over");
    handleFiles(e.dataTransfer.files);
});

document.getElementById("file-upload").addEventListener("change", (e) => handleFiles(e.target.files));
document.getElementById("folder-upload").addEventListener("change", (e) => handleFiles(e.target.files));

function handleFiles(fileList) {
    if (!fileList.length) return;

    dom.empty.style.display = "none";
    dom.fileList.classList.remove("hidden");
    dom.convertBtn.disabled = false;
    dom.convertBtn.classList.remove("opacity-50", "cursor-not-allowed");

    Array.from(fileList).forEach(file => {
        const type = getType(file);
        if (type === "unknown") return;

        const id = Math.random().toString(36).substr(2, 9);
        let defaultTarget = "mp4";
        if (type === "audio") defaultTarget = "mp3";
        if (type === "image") defaultTarget = "png";
        if (type === "document") defaultTarget = "pdf";

        files.push({ id, file, type, targetFormat: defaultTarget, status: "idle" });
        renderFileCard(id, file, type, defaultTarget);
    });
}

function renderFileCard(id, file, type, defaultTarget) {
    const div = document.createElement("div");
    div.id = "card-" + id;
    div.className = "bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex flex-col items-center gap-3 fade-in relative hover:shadow-md transition-all";

    const icon = type === "video" ? "🎬" : type === "audio" ? "🎵" : type === "document" ? "📄" : "🖼️";
    const options = FORMATS[type].map(fmt =>
        \`<option value="\${fmt}"\${fmt === defaultTarget ? " selected" : ""}>to \${fmt.toUpperCase()}</option>\`
    ).join("");

    div.innerHTML = \`
        <div class="absolute top-2 right-2">
             <button onclick="removeFile('\${id}')" class="text-slate-300 hover:text-red-500 p-1 rounded-full hover:bg-slate-50 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        </div>
        <div class="w-16 h-16 bg-slate-100 rounded-2xl flex items-center justify-center text-3xl flex-shrink-0 mb-1">\${icon}</div>
        <div class="w-full text-center">
            <h4 class="font-bold text-slate-700 truncate w-full px-2 text-sm" title="\${file.name}">\${file.name}</h4>
            <p class="text-xs text-slate-400 mt-0.5">\${(file.size / 1024 / 1024).toFixed(2)} MB</p>
        </div>
        <div class="flex flex-col items-center gap-2 w-full mt-1">
            <div class="flex items-center gap-2 text-xs text-slate-500">
                <span>Convert to:</span>
                <select onchange="updateTarget('\${id}', this.value)" class="bg-indigo-50 border-0 text-indigo-700 font-semibold text-xs rounded-md focus:ring-2 focus:ring-indigo-200 block py-1 px-2 cursor-pointer">
                    \${options}
                </select>
            </div>
        </div>
        <div id="action-\${id}" class="w-full mt-2">
             <div class="w-full bg-slate-100 rounded-full h-2 hidden overflow-hidden" id="progress-container-\${id}">
                <div class="bg-indigo-500 h-2 rounded-full progress-bar" style="width: 0%" id="progress-\${id}"></div>
            </div>
            <div id="status-text-\${id}" class="text-[10px] font-medium text-center text-slate-400 mt-1 h-4">Ready</div>
        </div>
    \`;

    dom.fileList.appendChild(div);
}

function updateTarget(id, val) {
    const f = files.find(x => x.id === id);
    if (f) f.targetFormat = val;
}

function removeFile(id) {
    files = files.filter(f => f.id !== id);
    document.getElementById("card-" + id).remove();
    if (files.length === 0) {
        dom.empty.style.display = "flex";
        dom.fileList.classList.add("hidden");
        dom.convertBtn.disabled = true;
        dom.convertBtn.classList.add("opacity-50", "cursor-not-allowed");
    }
}

async function convertAll() {
    const needsFFmpeg = files.some(f => f.type === "video" || f.type === "audio");
    if (needsFFmpeg && !ffmpeg) {
        alert("Video/Audio conversion requires FFmpeg engine. Only image and document conversion available in limited mode.");
        return;
    }
    dom.convertBtn.disabled = true;
    dom.convertBtn.innerText = "Converting...";
    for (const f of files) {
        if (f.status === "done") continue;
        await processFile(f);
    }
    dom.convertBtn.disabled = false;
    dom.convertBtn.innerText = "Convert All";
}

async function processFile(fObj) {
    const progBar = document.getElementById("progress-" + fObj.id);
    const progCont = document.getElementById("progress-container-" + fObj.id);
    const statusTxt = document.getElementById("status-text-" + fObj.id);
    const actionArea = document.getElementById("action-" + fObj.id);

    progCont.classList.remove("hidden");
    statusTxt.innerText = "Processing...";
    fObj.status = "processing";

    try {
        const { file, id, targetFormat, type } = fObj;

        if (type === "document") {
            await processDocumentFile(fObj, progBar, statusTxt, actionArea);
        } else if (type === "image") {
            await processImageFile(fObj, progBar, statusTxt, actionArea);
        } else {
            // Video/Audio processing with FFmpeg
            const inputName = "input_" + id + "." + file.name.split(".").pop();
            const outputName = "output_" + id + "." + targetFormat;
            ffmpeg.FS("writeFile", inputName, await fetchFile(file));
            ffmpeg.setProgress(({ ratio }) => {
                progBar.style.width = (ratio * 100) + "%";
                statusTxt.innerText = (ratio * 100).toFixed(0) + "%";
            });
            await ffmpeg.run("-i", inputName, outputName);
            const data = ffmpeg.FS("readFile", outputName);
            const blob = new Blob([data.buffer], { type: type + "/" + targetFormat });
            const url = URL.createObjectURL(blob);
            actionArea.innerHTML = \`<a href="\${url}" download="\${file.name.split(".")[0]}.\${targetFormat}" class="bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold py-2 px-4 rounded shadow block text-center">Download</a>\`;
            ffmpeg.FS("unlink", inputName);
            ffmpeg.FS("unlink", outputName);
        }
        fObj.status = "done";
    } catch (err) {
        console.error(err);
        statusTxt.innerText = "Error";
        statusTxt.classList.add("text-red-500");
    }
}

async function processDocumentFile(fObj, progBar, statusTxt, actionArea) {
    const { file, targetFormat } = fObj;

    if (targetFormat === "pdf") {
        statusTxt.innerText = "Reading document...";
        progBar.style.width = "25%";

        const arrayBuffer = await file.arrayBuffer();

        statusTxt.innerText = "Converting to HTML...";
        progBar.style.width = "50%";

        const result = await mammoth.convertToHtml({ arrayBuffer: arrayBuffer });
        const html = result.value;

        statusTxt.innerText = "Generating PDF...";
        progBar.style.width = "75%";

        const element = document.createElement("div");
        element.innerHTML = html;
        element.style.padding = "20px";
        element.style.fontFamily = "Arial, sans-serif";
        element.style.fontSize = "12px";
        element.style.lineHeight = "1.5";

        const opt = {
            margin: 1,
            filename: file.name.split(".")[0] + ".pdf",
            image: { type: "jpeg", quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: "in", format: "letter", orientation: "portrait" }
        };

        const pdfBlob = await html2pdf().set(opt).from(element).output("blob");

        progBar.style.width = "100%";
        statusTxt.innerText = "Complete";

        const url = URL.createObjectURL(pdfBlob);
        actionArea.innerHTML = \`<a href="\${url}" download="\${file.name.split(".")[0]}.pdf" class="bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold py-2 px-4 rounded shadow block text-center">Download</a>\`;
    }
}

async function processImageFile(fObj, progBar, statusTxt, actionArea) {
    const { file, targetFormat } = fObj;

    statusTxt.innerText = "Processing image...";
    progBar.style.width = "50%";

    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();

    return new Promise((resolve, reject) => {
        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.drawImage(img, 0, 0);

            progBar.style.width = "100%";
            statusTxt.innerText = "Complete";

            canvas.toBlob((blob) => {
                const url = URL.createObjectURL(blob);
                actionArea.innerHTML = \`<a href="\${url}" download="\${file.name.split(".")[0]}.\${targetFormat}" class="bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold py-2 px-4 rounded shadow block text-center">Download</a>\`;
                resolve();
            }, "image/" + targetFormat);
        };
        img.onerror = reject;
        img.src = URL.createObjectURL(file);
    });
}`;
const PDF_SCRIPT = `pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.worker.min.js";

const TOOLS = [
    { id: "merge", icon: "📚", color: "bg-indigo-50 text-indigo-600", title: "Merge PDF", desc: "Combine multiple files & reorder pages." },
    { id: "organize", icon: "✂️", color: "bg-rose-50 text-rose-500", title: "Split & Edit", desc: "Rotate, delete, or extract specific pages.", type: "pages" },
    { id: "img2pdf", icon: "🖼️", color: "bg-emerald-50 text-emerald-600", title: "Image to PDF", desc: "Convert JPG/PNG to PDF documents.", accept: "image/*" },
    {
        id: "watermark", icon: "💧", color: "bg-blue-50 text-blue-500", title: "Watermark", desc: "Add text overlay to pages.", inputs: [
            { id: "wm-text", type: "text", placeholder: "Watermark Text", width: "w-48" },
            { id: "wm-color", type: "select", options: ["Red", "Grey", "Blue"], width: "w-24" }
        ]
    },
    { id: "numbers", icon: "🔢", color: "bg-slate-50 text-slate-600", title: "Page Numbers", desc: "Add pagination to footer." },
    {
        id: "protect", icon: "🔒", color: "bg-orange-50 text-orange-600", title: "Protect", desc: "Encrypt with password.", inputs: [
            { id: "pass-set", type: "password", placeholder: "Set Password", width: "w-40" }
        ]
    },
    {
        id: "unlock", icon: "🔓", color: "bg-teal-50 text-teal-600", title: "Unlock", desc: "Remove PDF password.", inputs: [
            { id: "pass-unlock", type: "password", placeholder: "Original Password", width: "w-40" }
        ]
    },
    {
        id: "metadata", icon: "🏷️", color: "bg-purple-50 text-purple-600", title: "Metadata", desc: "Edit Title & Author.", inputs: [
            { id: "meta-title", type: "text", placeholder: "New Title", width: "w-40" },
            { id: "meta-author", type: "text", placeholder: "New Author", width: "w-40" }
        ]
    },
    { id: "flatten", icon: "🔨", color: "bg-gray-50 text-gray-600", title: "Flatten", desc: "Make forms un-editable." }
];

const app = { activeTool: null, files: [], sortable: null };

const dom = {
    dash: document.getElementById("view-dashboard"),
    grid: document.getElementById("tool-grid"),
    work: document.getElementById("view-workspace"),
    workGrid: document.getElementById("grid-container"),
    settings: document.getElementById("tool-settings"),
    title: document.getElementById("tool-name"),
    empty: document.getElementById("empty-state"),
    input: document.getElementById("file-upload"),
    toast: document.getElementById("toast"),
    toastMsg: document.getElementById("toast-msg")
};

function initDashboard() {
    dom.grid.innerHTML = "";
    TOOLS.forEach(t => {
        const div = document.createElement("button");
        div.className = "tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4";
        div.onclick = () => launchTool(t.id);
        div.innerHTML = \`<div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl \${t.color}">\${t.icon}</div><div><h4 class="font-bold text-lg text-slate-800">\${t.title}</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">\${t.desc}</p></div>\`;
        dom.grid.appendChild(div);
    });
}
initDashboard();

function launchTool(toolId) {
    app.activeTool = toolId;
    const conf = TOOLS.find(t => t.id === toolId);

    dom.dash.classList.add("hidden");
    dom.work.classList.remove("hidden");
    dom.title.innerText = conf.title;
    dom.input.accept = conf.accept || ".pdf";
    dom.input.value = "";

    renderSettings(conf.inputs || []);
    initSortable();
}

function goHome() {
    dom.work.classList.add("hidden");
    dom.dash.classList.remove("hidden");
    resetWorkspace();
}

function renderSettings(inputs) {
    dom.settings.innerHTML = "";

    if (app.activeTool === "organize") {
        const grp = document.createElement("div");
        grp.className = "flex gap-2 bg-slate-100 p-1.5 rounded-lg";
        grp.innerHTML = \`<button onclick="rotateSelected(90)" class="px-3 py-1.5 bg-white rounded shadow-sm text-sm font-semibold hover:text-indigo-500">↻ 90°</button><button onclick="deleteSelected()" class="px-3 py-1.5 bg-white rounded shadow-sm text-sm font-semibold hover:text-red-600 text-red-500">🗑 Delete</button>\`;
        dom.settings.appendChild(grp);
    }

    inputs.forEach(inp => {
        if (inp.type === "select") {
            const sel = document.createElement("select");
            sel.id = inp.id;
            sel.className = \`p-2 rounded-lg border border-slate-300 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none \${inp.width}\`;
            inp.options.forEach(o => {
                const opt = document.createElement("option");
                opt.value = o;
                opt.innerText = o;
                sel.appendChild(opt);
            });
            dom.settings.appendChild(sel);
        } else {
            const i = document.createElement("input");
            i.id = inp.id;
            i.type = inp.type;
            i.placeholder = inp.placeholder;
            i.className = \`p-2 rounded-lg border border-slate-300 text-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none \${inp.width}\`;
            dom.settings.appendChild(i);
        }
    });
}

dom.input.addEventListener("change", async (e) => {
    if (!e.target.files.length) return;
    showToast("Processing files...", true);
    dom.empty.classList.add("hidden");

    for (const file of e.target.files) {
        await addFileToGrid(file);
    }
    hideToast();
});

async function addFileToGrid(file) {
    const id = Math.random().toString(36).substr(2, 9);
    const isPdf = file.type === "application/pdf";
    const conf = TOOLS.find(t => t.id === app.activeTool);

    if (conf.type === "pages" && isPdf) {
        const buff = await file.arrayBuffer();
        const pdf = await pdfjsLib.getDocument(buff).promise;

        for (let i = 1; i <= pdf.numPages; i++) {
            const div = createCard(id, true);
            div.dataset.fileId = id;
            div.dataset.pageIdx = i - 1;
            div.dataset.rotation = 0;

            await renderThumbnail(pdf, i, div.querySelector(".thumb-area"));

            const num = document.createElement("span");
            num.className = "absolute bottom-2 right-2 bg-slate-900/70 text-white text-[10px] font-bold px-1.5 py-0.5 rounded";
            num.innerText = i;
            div.querySelector(".thumb-area").appendChild(num);

            div.onclick = (e) => {
                if (!e.target.closest("button")) {
                    div.querySelector(".thumb-area").classList.toggle("selected");
                }
            };
            dom.workGrid.appendChild(div);
        }
        app.files.push({ id, file, buffer: buff });
    } else {
        const div = createCard(id, false);
        div.dataset.fileId = id;

        const thumbArea = div.querySelector(".thumb-area");
        if (isPdf) {
            const buff = await file.arrayBuffer();
            const pdf = await pdfjsLib.getDocument(buff).promise;
            await renderThumbnail(pdf, 1, thumbArea);
        } else {
            const img = document.createElement("img");
            img.src = URL.createObjectURL(file);
            img.className = "w-full h-full object-contain";
            thumbArea.appendChild(img);
        }

        const name = document.createElement("div");
        name.className = "w-full text-center px-4 pb-4";
        name.innerHTML = \`<h4 class="font-bold text-slate-700 truncate w-full text-sm" title="\${file.name}">\${file.name}</h4><p class="text-xs text-slate-400 mt-0.5">\${(file.size / 1024 / 1024).toFixed(2)} MB</p>\`;
        div.appendChild(name);

        dom.workGrid.appendChild(div);
        app.files.push({ id, file });
    }
}

function createCard(id, isPage) {
    const div = document.createElement("div");
    div.className = "group relative bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col items-center gap-3 hover:shadow-md transition-all select-none";

    // Drag Handle
    const handle = document.createElement("div");
    handle.className = "drag-handle absolute top-2 left-2 bg-white/90 backdrop-blur p-1.5 rounded-lg shadow-sm border border-slate-100 cursor-grab z-10 text-slate-400 hover:text-indigo-500 transition-colors";
    handle.innerHTML = \`<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="5" r="1"/><circle cx="9" cy="12" r="1"/><circle cx="9" cy="19" r="1"/><circle cx="15" cy="5" r="1"/><circle cx="15" cy="12" r="1"/><circle cx="15" cy="19" r="1"/></svg>\`;
    div.appendChild(handle);

    // Delete Button
    const del = document.createElement("button");
    del.className = "absolute top-2 right-2 text-slate-300 hover:text-red-500 p-1 rounded-full hover:bg-slate-50 transition-colors z-20";
    del.innerHTML = \`<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>\`;
    del.onclick = (e) => { e.stopPropagation(); div.remove(); };
    div.appendChild(del);

    const thumb = document.createElement("div");
    thumb.className = \`thumb-area w-full \${isPage ? "h-48" : "h-32"} bg-slate-50 relative overflow-hidden flex items-center justify-center mt-3\`;
    div.appendChild(thumb);

    return div;
}

async function renderThumbnail(pdf, pageNum, container) {
    try {
        const page = await pdf.getPage(pageNum);
        const viewport = page.getViewport({ scale: 0.6 });
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        canvas.width = viewport.width;
        canvas.height = viewport.height;
        canvas.className = "w-full h-full object-contain";
        await page.render({ canvasContext: ctx, viewport: viewport }).promise;
        container.appendChild(canvas);
    } catch (e) {
        container.innerText = "Preview N/A";
    }
}

function initSortable() {
    if (app.sortable) app.sortable.destroy();
    app.sortable = new Sortable(dom.workGrid, {
        animation: 200,
        handle: ".drag-handle",
        ghostClass: "sortable-ghost",
        dragClass: "sortable-drag",
        onStart: () => document.body.style.cursor = "grabbing",
        onEnd: () => document.body.style.cursor = "default"
    });
}

function rotateSelected(deg) {
    document.querySelectorAll(".thumb-area.selected").forEach(el => {
        const card = el.closest("div[data-rotation]");
        let r = parseInt(card.dataset.rotation) || 0;
        r = (r + deg) % 360;
        card.dataset.rotation = r;
        el.querySelector("canvas").style.transform = \`rotate(\${r}deg)\`;
    });
}

function deleteSelected() {
    document.querySelectorAll(".thumb-area.selected").forEach(el => {
        el.closest(".group").remove();
    });
}

function resetWorkspace() {
    app.files = [];
    app.activeTool = null;
    dom.workGrid.innerHTML = "";
    dom.empty.classList.remove("hidden");
}

async function processFiles() {
    if (dom.workGrid.children.length === 0) return alert("Please add files first.");
    showToast("Generating PDF...", true);

    const { PDFDocument, rgb, degrees, StandardFonts } = PDFLib;

    try {
        const newPdf = await PDFDocument.create();
        const cards = Array.from(dom.workGrid.children);
        const conf = TOOLS.find(t => t.id === app.activeTool);

        if (conf.type === "pages") {
            const pdfCache = {};
            for (const f of app.files) pdfCache[f.id] = await PDFDocument.load(f.buffer);

            for (const card of cards) {
                const fid = card.dataset.fileId;
                const pIdx = parseInt(card.dataset.pageIdx);
                const rot = parseInt(card.dataset.rotation);

                const [page] = await newPdf.copyPages(pdfCache[fid], [pIdx]);
                if (rot !== 0) page.setRotation(degrees(page.getRotation().angle + rot));
                newPdf.addPage(page);
            }
        } else {
            for (const card of cards) {
                const fObj = app.files.find(f => f.id === card.dataset.fileId);

                if (fObj.file.type.includes("image")) {
                    const imgBuff = await fObj.file.arrayBuffer();
                    let img = fObj.file.type.includes("png") ? await newPdf.embedPng(imgBuff) : await newPdf.embedJpg(imgBuff);
                    const p = newPdf.addPage([img.width, img.height]);
                    p.drawImage(img, { x: 0, y: 0, width: img.width, height: img.height });
                } else {
                    const srcBuff = await fObj.file.arrayBuffer();
                    let srcPdf;

                    if (app.activeTool === "unlock") {
                        const pass = document.getElementById("pass-unlock").value;
                        try { srcPdf = await PDFDocument.load(srcBuff, { password: pass }); }
                        catch { throw new Error("Incorrect Password"); }
                    } else {
                        srcPdf = await PDFDocument.load(srcBuff);
                    }

                    const pgs = await newPdf.copyPages(srcPdf, srcPdf.getPageIndices());
                    pgs.forEach(p => newPdf.addPage(p));
                }
            }
        }

        const pages = newPdf.getPages();

        if (app.activeTool === "watermark") {
            const text = document.getElementById("wm-text").value || "DRAFT";
            const colorName = document.getElementById("wm-color").value;
            const col = colorName === "Red" ? [1, 0, 0] : colorName === "Blue" ? [0, 0, 1] : [0.5, 0.5, 0.5];
            const font = await newPdf.embedFont(StandardFonts.HelveticaBold);

            pages.forEach(p => {
                const { width, height } = p.getSize();
                p.drawText(text, {
                    x: width / 2 - (text.length * 15), y: height / 2,
                    size: 60, font: font, color: rgb(...col),
                    opacity: 0.3, rotate: degrees(45)
                });
            });
        }

        if (app.activeTool === "numbers") {
            const font = await newPdf.embedFont(StandardFonts.Courier);
            pages.forEach((p, i) => {
                p.drawText(\`\${i + 1} / \${pages.length}\`, {
                    x: p.getWidth() - 100, y: 20, size: 10, font: font, color: rgb(0, 0, 0)
                });
            });
        }

        if (app.activeTool === "metadata") {
            const t = document.getElementById("meta-title").value;
            const a = document.getElementById("meta-author").value;
            if (t) newPdf.setTitle(t);
            if (a) newPdf.setAuthor(a);
        }

        if (app.activeTool === "flatten") newPdf.getForm().flatten();
        if (app.activeTool === "protect") {
            const pw = document.getElementById("pass-set").value;
            if (pw) newPdf.encrypt({ userPassword: pw, ownerPassword: pw });
        }

        const pdfBytes = await newPdf.save();
        const blob = new Blob([pdfBytes], { type: "application/pdf" });
        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = \`111iridescence_\${app.activeTool}.pdf\`;
        link.click();

        showToast("Success! Downloading...", false);
        setTimeout(hideToast, 2000);

    } catch (err) {
        console.error(err);
        alert(err.message);
        hideToast();
    }
}

function showToast(msg, loading) {
    dom.toastMsg.innerText = msg;
    dom.toast.classList.remove("translate-y-32", "opacity-0");
    dom.toast.querySelector(".loader").style.display = loading ? "block" : "none";
}

function hideToast() {
    dom.toast.classList.add("translate-y-32", "opacity-0");
}`;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Common headers for SharedArrayBuffer support
    const headers = {
      "Cross-Origin-Embedder-Policy": "require-corp",
      "Cross-Origin-Opener-Policy": "same-origin",
    };

    // --- 1. ROOT PATH (App Hub) ---
    if (url.pathname === "/") {
      return new Response(renderIndex(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 2. CSS STYLESHEET ---
    if (url.pathname === "/style.css") {
      return new Response(TAILWIND_CSS, {
        headers: { "Content-Type": "text/css" },
      });
    }

    // --- 3. CONVERTER APP ---
    if (url.pathname === "/converter") {
      return new Response(renderConverter(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 4. PDF TOOLS APP ---
    if (url.pathname === "/pdf") {
      return new Response(renderPDFTools(), {
        headers: { 
          "Content-Type": "text/html; charset=utf-8",
          ...headers
        },
      });
    }

    // --- 404 NOT FOUND ---
    return new Response("404 - Page Not Found", { status: 404 });
  }
};

function renderIndex() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | App Hub</title>
    <link rel="stylesheet" href="/style.css">
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 select-none">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">iridescence</span></h1>
        </div>
        <div class="hidden md:flex items-center gap-2 text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200">
            <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            ALL SYSTEMS OPERATIONAL
        </div>
    </header>
    <main class="flex-1 overflow-y-auto p-6 md:p-10 fade-in">
        <div class="max-w-7xl mx-auto space-y-12 pb-20">
            <div>
                <h2 class="text-4xl font-extrabold mb-2 text-slate-900 tracking-tight">App Hub</h2>
                <p class="text-lg text-slate-500 max-w-2xl">Access all your tools, vaults, and projects from one secure location.</p>
            </div>
            <section>
                <div class="flex items-center gap-2 mb-6"><span class="text-2xl">🛠️</span><h3 class="text-xl font-bold text-slate-800">Tools</h3></div>
                <div class="grid grid-cols-2 lg:grid-cols-4 gap-5">
                    <a href="/pdf" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-indigo-50 text-indigo-600 transition-transform group-hover:scale-110">📚</div>
                        <div><h4 class="font-bold text-lg text-slate-800">111 PDF Tools</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Secure, client-side PDF editing and merging suite.</p></div>
                    </a>
                    <a href="/converter" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-emerald-50 text-emerald-600 transition-transform group-hover:scale-110">🔄</div>
                        <div><h4 class="font-bold text-lg text-slate-800">111 Converter</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Fast universal file conversion utility.</p></div>
                    </a>
                </div>
            </section>
            <hr class="border-slate-200">
            <section>
                <div class="flex items-center gap-2 mb-6"><span class="text-2xl">✨</span><h3 class="text-xl font-bold text-slate-800">Other Webapps</h3></div>
                <div class="grid grid-cols-2 lg:grid-cols-4 gap-5">
                    <a href="/vault" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-slate-100 text-slate-600 transition-transform group-hover:scale-110">🔒</div>
                        <div><h4 class="font-bold text-lg text-slate-800">Vault</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Secure personal storage and data archive.</p></div>
                    </a>
                    <a href="/habits" class="tool-card bg-white p-6 rounded-2xl border border-slate-200 text-left flex flex-col items-start gap-4 no-underline group">
                        <div class="w-14 h-14 rounded-xl flex items-center justify-center text-3xl bg-orange-50 text-orange-600 transition-transform group-hover:scale-110">📈</div>
                        <div><h4 class="font-bold text-lg text-slate-800">Habits Tracker</h4><p class="text-sm text-slate-500 mt-1 leading-relaxed">Daily routines, goals, and progress monitoring.</p></div>
                    </a>
                </div>
            </section>
        </div>
    </main>
</body>
</html>`;
}

function renderConverter() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | Universal Converter</title>
    <link rel="stylesheet" href="/style.css">
    <script src="https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js"></script>
    <script src="https://unpkg.com/mammoth@1.6.0/mammoth.browser.min.js"></script>
    <script src="https://unpkg.com/html2pdf.js@0.10.1/dist/html2pdf.bundle.min.js"></script>
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 cursor-pointer select-none" onclick="window.location.href='/'">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">converter</span></h1>
        </div>
        <div id="engine-status" class="flex items-center gap-2 text-xs font-semibold text-orange-500 bg-orange-50 px-3 py-1.5 rounded-full border border-orange-200">
            <span class="w-2 h-2 rounded-full bg-orange-500 animate-pulse"></span>
            Loading Engine...
        </div>
    </header>

    <main class="flex-1 overflow-hidden relative flex flex-col">
        <div class="bg-white border-b border-slate-200 p-4 flex flex-col md:flex-row items-center justify-between shadow-sm z-10 gap-4">
            <div class="text-sm text-slate-500 font-medium">
                Supports: <span class="text-slate-800">Video, Audio, Images, Documents</span>
            </div>

            <div class="flex items-center gap-3">
                <button onclick="document.getElementById('folder-upload').click()" class="bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2 rounded-lg font-bold text-sm border border-slate-200">
                    📂 Add Folder
                </button>
                <button onclick="document.getElementById('file-upload').click()" class="bg-slate-800 hover:bg-slate-900 text-white px-4 py-2 rounded-lg font-bold text-sm shadow-md">
                    + Add Files
                </button>
                <button id="convert-all-btn" onclick="convertAll()" class="bg-indigo-500 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg font-bold text-sm shadow-md transition-all opacity-50 cursor-not-allowed" disabled>
                    Convert All
                </button>
            </div>
        </div>

        <div id="drop-zone" class="flex-1 overflow-y-auto p-4 md:p-8 relative bg-slate-50">
            <div id="empty-state" class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none opacity-100 transition-opacity">
                <div class="w-24 h-24 bg-indigo-50 rounded-full flex items-center justify-center text-5xl mb-6 text-indigo-500 shadow-inner">♻️</div>
                <h3 class="text-2xl font-bold text-slate-700 mb-2">Universal Converter</h3>
                <p class="text-slate-500 text-center max-w-md">Drag & Drop files or folders here.<br>Convert MP4, AVI, MOV, MP3, WAV, PNG, JPG, WEBP, DOCX and more.</p>
            </div>
            <div id="file-list" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 max-w-5xl mx-auto pb-20 hidden"></div>
        </div>

        <input type="file" id="file-upload" class="hidden" multiple>
        <input type="file" id="folder-upload" class="hidden" multiple webkitdirectory directory>
    </main>

    <script>${CONVERTER_SCRIPT}</script>
</body>
</html>`;
}

function renderPDFTools() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>111iridescence | PDF Tools</title>
    <link rel="stylesheet" href="/style.css">
    <script src="https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.15.0/Sortable.min.js"></script>
</head>
<body class="h-screen flex flex-col overflow-hidden text-slate-800 font-sans bg-slate-50">
    <header class="bg-white border-b border-slate-200 h-16 flex items-center px-6 justify-between flex-shrink-0 z-20">
        <div class="flex items-center gap-3 cursor-pointer select-none" onclick="window.location.href='/'">
            <div class="w-8 h-8 bg-gradient-to-br from-indigo-500 to-rose-500 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-lg">111</div>
            <h1 class="font-bold text-xl tracking-tight">111<span class="text-indigo-500">iridescence</span></h1>
        </div>
        <div class="hidden md:flex items-center gap-2 text-xs font-semibold text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200">
            <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            CLIENT-SIDE ONLY
        </div>
    </header>

    <main class="flex-1 overflow-hidden relative">
        <div id="view-dashboard" class="h-full overflow-y-auto p-6 md:p-10 fade-in">
            <div class="max-w-7xl mx-auto">
                <div class="mb-12">
                    <h2 class="text-3xl font-bold mb-2 text-slate-900">PDF Tools</h2>
                    <p class="text-slate-500">Secure processing in your browser.</p>
                </div>
                <div class="grid grid-cols-2 lg:grid-cols-4 gap-5" id="tool-grid"></div>
            </div>
        </div>

        <div id="view-workspace" class="hidden h-full flex flex-col bg-slate-50">
            <div class="bg-white border-b border-slate-200 p-4 flex flex-col md:flex-row items-center justify-between shadow-sm z-10 gap-4">
                <div class="flex items-center gap-4 w-full md:w-auto">
                    <button onclick="goHome()" class="text-slate-500 hover:text-slate-800 font-medium px-2 py-1 hover:bg-slate-100 rounded">← Back</button>
                    <div class="h-6 w-px bg-slate-200 hidden md:block"></div>
                    <h2 id="tool-name" class="font-bold text-lg text-slate-800">Tool Name</h2>
                </div>
                <div id="tool-settings" class="flex-1 flex flex-wrap items-center justify-center md:justify-end gap-3"></div>
                <div class="flex items-center gap-2 w-full md:w-auto justify-end">
                    <button onclick="document.getElementById('file-upload').click()" class="bg-slate-100 hover:bg-slate-200 text-slate-700 px-4 py-2 rounded-lg font-bold text-sm border border-slate-200">
                        + Add Files
                    </button>
                    <button id="btn-process" onclick="processFiles()" class="bg-indigo-500 hover:bg-indigo-600 text-white px-6 py-2 rounded-lg font-bold text-sm shadow-md transition-all flex items-center gap-2">
                        Download PDF
                    </button>
                </div>
            </div>

            <div id="canvas-area" class="flex-1 overflow-y-auto p-4 md:p-8 relative">
                <div id="empty-state" class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none opacity-60">
                    <div class="w-24 h-24 bg-slate-200 rounded-full flex items-center justify-center text-4xl mb-4 text-slate-400">📂</div>
                    <h3 class="text-xl font-bold text-slate-400">Drop files here</h3>
                </div>
                <div id="grid-container" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto pb-20"></div>
            </div>
            <input type="file" id="file-upload" class="hidden" multiple>
        </div>
    </main>

    <div id="toast" class="fixed bottom-6 right-6 bg-slate-800 text-white px-6 py-4 rounded-lg shadow-2xl transform translate-y-32 opacity-0 transition-all duration-300 z-50 flex items-center gap-4">
        <div class="loader"></div>
        <span id="toast-msg" class="font-medium">Processing...</span>
    </div>

    <script>${PDF_SCRIPT}</script>
</body>
</html>`;
}